// <auto-generated />
namespace ElevenNote.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _2ndupae : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2ndupae));
        
        string IMigrationMetadata.Id
        {
            get { return "201906271514590_2nd upae"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
